server:
  port: 8085
  servlet:
    context-path: /search

spring:
  application:
    name: search-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  elasticsearch:
    uris: http://localhost:9200

app:
  topics:
    postCreated: post-created
    postUpdated: post-updated
    postDeleted: post-deleted
  index:
    posts: posts
  services:
    post:
      base-url: http://localhost:8083/post

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics


